version: '2'

services:
  nginx:
    image: nginx
    container_name: nginx_proxy
    ports:
     - 80:80
     - 443:443 
    networks:
      - net_web
      - docker_elk
    volumes:
     - /home/infra/frontend/nginx_proxy/conf.d:/etc/nginx/conf.d
     - /home/infra/frontend/nginx_proxy/vhost.d:/etc/nginx/vhost.d
     - /usr/share/nginx/html
     - /etc/nginx/certs
     - /home/certs:/etc/nginx/certs:ro
    logging:
      driver: fluentd
      options:
        tag: "frontend/nginx-proxy"
        fluentd-address: "172.22.0.2:24224"
        fluentd-async-connect: "true"
    restart: always
  nginxgen:
    image: jwilder/docker-gen
    container_name: docker_gen
    networks:
     - net_proxy_tiers
     - docker_elk
    volumes_from:
     - nginx
    volumes:
     - /home/infra/frontend/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
     - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx_proxy -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    logging:
      driver: fluentd
      options:
       tag: "frontend/docker-gen"
       fluentd-address: "172.22.0.2:24224"
       fluentd-async-connect: "true"
    restart: always
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    networks:
     - net_proxy_tiers
     - docker_elk
    volumes_from:
     - nginx
    volumes:
     - /home/certs:/etc/nginx/certs:rw
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
     - NGINX_DOCKER_GEN_CONTAINER=docker_gen
    logging:
      driver: fluentd
      options:
        tag: "frontend/letsencrypt"
        fluentd-address: "172.22.0.2:24224"
        fluentd-async-connect: "true"
    restart: always
networks:
  net_web:
    external: true
  net_proxy_tiers:
    external: true
  docker_elk:
    external:
      name: elk_docker_elk
